### ISSUE TITLE
Suggestions on the website

### ISSUE THREAD

**Issue by Jamie-VESoft** [vesoft-inc/nebula-website#16]
1. Change the menu name Content to Resources
<img width="227" alt="image" src="https://user-images.githubusercontent.com/57335825/73819002-83c7f480-4829-11ea-8f98-2bbfbca7ecf8.png">

2. The link to the Docs item should be: docs.nebula-graph.io

3. The link to Get Started should be: https://docs.nebula-graph.io/manual-EN/1.overview/2.quick-start/1.get-started/#batch-inserting
<img width="577" alt="image" src="https://user-images.githubusercontent.com/57335825/73823090-7e22dc80-4832-11ea-98d8-e127bdd95d56.png">

4. Blog should have author and publishing date options

5. Need to be able to get back to the home page when visitors are in the Blog section

6. Issues on the footer:

     1) The WeChat icon is not aligned well with others

     2) Remove the Subscribe option

     3) Fix all indirect links

     4) Hide the Company section since we don't have those pages yet

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/57335825/73823414-246ee200-4833-11ea-8f86-d0e48a1a653d.png">

**Comment by nianiaJR** [comment]
All things have been fixed or modified except 4, because I think both author and publish date are content of the blog itselft. So it can be done by the markdown writer instead of the blog template.
