### ISSUE TITLE
Twitter failed to fetch the featured image of our posts

### ISSUE THREAD

**Issue by Jamie-VESoft** [vesoft-inc/nebula-website#30]
I was trying to post our latest article on Twitter and found that Twitter failed to fetch the featured image as well as meta title and description in the preview snippet. 

How it looks upon success:
![image](https://user-images.githubusercontent.com/57335825/74894846-12607800-53cb-11ea-831a-15f3f5f1e2e6.png)

How it looks upon failure:
![image](https://user-images.githubusercontent.com/57335825/74894895-2b692900-53cb-11ea-863c-db4945092c6e.png)

Here's a discussion on this issue: https://discourse.gohugo.io/t/academic-theme-unable-to-get-page-post-featured-images-on-twitter-card/18864/6

Please be sure to add **featured image AND meta info**

**Comment by nianiaJR** [comment]
done.
![Uploading image.png…]()
