### ISSUE TITLE
Read the value of the description field as the summary of each post on the blog home page

### ISSUE THREAD

**Issue by Jamie-VESoft** [vesoft-inc/nebula-website#32]
The value of description field as summary of each post. See below:

![image](https://user-images.githubusercontent.com/57335825/75001968-e530ca00-549d-11ea-8aec-7bec20576396.png)

**Comment by nianiaJR** [comment]
done
![image](https://user-images.githubusercontent.com/8124783/75429669-2127cb80-5985-11ea-9cf9-d607d04aac8f.png)
