### ISSUE TITLE
About the rss feed 

### ISSUE THREAD

**Issue by Jamie-VESoft** [vesoft-inc/nebula-website#54]
1) Featured images cannot be retrieved by RSS readers
2) Change the title of rss-feed to Nebula Graph Blog - Everything about Graph Databases

**Comment by nianiaJR** [comment]
1. Image has been added:
![image](https://user-images.githubusercontent.com/8124783/76278972-f3694d80-62c7-11ea-838f-5c337be47ead.png)
2. This title maybe just for the website title, which means to tell the reader where the post come from, not the description of the post.
